### ISSUE TITLE
Congrats!

### ISSUE THREAD

**Issue by mscuthbert** [mehaase/pep-0505#2]
Not really an issue, but I wasn't sure where to put a congrats note now that discussion on python-ideas has trickled down, but I think that this is a major piece of work and I hope that at least some substantial parts of it make their way into the Python language in the future!

As a meta comment about new keywords, I'm not sure that the "Python 4 won't be like Python 3" document says that incompatible changes need to wait until Py4 and that there'd be major resistance.  It does say that PEP 387 is still in force, and I think there's an argument to be made that this operator could be something like the "with" statement and be worth phasing in with a from __future__ period, especially if the operator name was rarely if ever found in existing code.

(Not to add to the spelling wars, but I'm fond of "otherwise" for the eggplant operator; it may seem long, but it seems clear ("path = file otherwise url"), rarely used, and even at 9 characters it still beats the 21 characters + the length of the variable over "path = file if file is not None else url") 

but really saying thanks and encouraging this being worth adding a keyword was the reason for the issue.  Feel free to close immediately!

**Comment by mehaase** [comment]
Thank you for the positive feedback!
